### ISSUE TITLE
重复发送问题

### ISSUE THREAD

**Issue by jie65535** [Samarium150/mirai-console-loafers-calendar#2]
![log](https://user-images.githubusercontent.com/29452349/164603741-822380e1-d97e-443d-98e8-f186840ee1d4.png)
log中是向两个群各发送一张图，实际上第一个群收到了3张，第二个群收到了2张。

![image](https://user-images.githubusercontent.com/29452349/164603766-b04ccda9-c70d-4bec-897b-ef04f1d178bf.png)

在十一点多时，我在做其它事情，重启了几次系统。

**Comment by Samarium150** [comment]
需要能稳定复现的方法才能定位问题
