### ISSUE TITLE
图片发送错误

### ISSUE THREAD

**Issue by BaJie041012** [Samarium150/mirai-console-loafers-calendar#5]
我是小白，不会看后台，前台目前状况是:在一次 slc 订阅后，无论 lc 或者 slc 都输出一张周日不摸鱼的图片，见附，插件是最新，按照教程配置的，目前在我自己电脑、服务器上都是这种情况我不太清楚怎么复现，没有别的电脑做实验了

**Comment by BaJie041012** [comment]
![Uploading Image_1710373036155.png…]()

**Comment by BaJie041012** [comment]
![Image_1710373036155](https://github.com/Samarium150/mirai-console-loafers-calendar/assets/160606914/ad042d6a-57d7-4c02-af3c-8ada9ecc7e4f)

**Comment by Samarium150** [comment]
应该是接口没更新的问题，我之后把另一个接口作为备份加进来
